# cargo-deny configuration for supply chain security
# https://github.com/EmbarkStudios/cargo-deny

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]

[licenses]
# The confidence threshold for detecting a license from a license text.
# 0.8 = 80% confidence
confidence-threshold = 0.8
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "Unicode-3.0",
    "CC0-1.0",
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "warn"
# Skip certain crates when checking for duplicates
skip = []
# Explicitly denied crates
deny = []

[sources]
# Lint level for crates that do not have a version published that matches
# the version requirement
unknown-registry = "warn"
# Lint level for crates that have a version published that matches the
# version requirement but the version is yanked
unknown-git = "warn"
# List of allowed registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of allowed Git repositories
allow-git = []