permissions:
  contents: read
name: Cargo Deny

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  schedule:
    - cron: '0 4 * * 1'  # Weekly on Monday at 4 AM UTC

jobs:
  deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@8410ad4602e4e96c55d6f3fa122c21dd44ea8f17 # v4
      
    - name: Run cargo-deny
      uses: EmbarkStudios/cargo-deny-action@8371184bd11e21dcf8ac82ebf8c9c9f74ebf7268 # v2
      with:
        arguments: --all-features